python ./memnets/scripts/train_memnets.py \
    --seed 1 \
    --device 'cpu' \
    --lagtimes 1 7 8 9 10 \
    --encoder_sizes 30 30 30 30 10 3 \
    --decay_rate 0.002 \
    --thres 0.05 \
    --learning_rate 0.001 \
    --n_epochs 100 \
    --train_split 0.9 \
    --train_batch_size 10000 \
    --data_directory ./memnets/data/alanine_dipeptide/cartesian_coordinates \
    --saving_directory . 
